name: Deploy to Github Pages

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Github Pages

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x

    - name: Install NPM packages
      run: npm install && npm ci
    
    - name: Build project
      run: npm run build